version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-{{ checksum "requirements.txt" }}-{{ checksum "volatile-requirements.txt" }}-{{ checksum "dev-requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            # patch for weirdness in mirrors - https://discuss.circleci.com/t/circleci-failing-when-using-sudo-apt-get-update/29269/9
            sudo sed -i '/jessie-backports/d' /etc/apt/sources.list
            sudo sed -i '/jessie-updates/d' /etc/apt/sources.list
            sudo apt-get -qq update
            sudo apt-get -qq upgrade
            sudo apt-get -qq install libfftw3-dev libeigen3-dev build-essential libcfitsio-bin
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip setuptools numpy cython pybind11
            pip install --progress-bar=off -r dev-requirements.txt
            pip install galsim
            pip install --progress-bar=off -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-{{ checksum "requirements.txt" }}-{{ checksum "volatile-requirements.txt" }}-{{ checksum "dev-requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install -U --progress-bar=off --no-cache-dir --upgrade-strategy=eager --force-reinstall -r volatile-requirements.txt
            pip install -q --progress-bar=off --no-cache-dir --force-reinstall .
            flake8 metadetect
            flake8 bin

            pytest -vv metadetect
