name: lsst-tests

on:
  push:
    branches:
      - lsst-dev
      - main
      - master
  pull_request: null
  workflow_dispatch: null
  schedule:
    - cron: 0 23 * * 4

jobs:
  lsst-tests:
    name: lsst-tests
    strategy:
      matrix:
        pyver: ["3.12"]

    runs-on: "ubuntu-latest"

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.pyver }}
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda install --quiet --yes --file requirements.txt
          conda install --quiet --yes --file dev-requirements.txt
          conda install -q -y stackvana=0 lsstdesc-weaklensingdeblending
          conda install lsstdesc-wl-shear-sims

          pip install --no-deps git+https://github.com/LSSTDESC/descwl_coadd.git

          python -m pip install -e .

      - name: test ngmix w/ conda latest
        shell: bash -l {0}
        run: |
          # we run metadetect/tests and metadetect/lsst/tests
          pytest -v -n 4 --cov=metadetect --cov-report=xml --cov-report=term-missing --cov-branch metadetect

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

  notify-on-failure:
    runs-on: ubuntu-latest
    if: ${{ always() && (github.event_name == 'push' || github.event_name == 'schedule') && needs.lsst-tests.result == 'failure' }}
    needs:
      - lsst-tests
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        MSG_MINIMAL: actions url
        SLACK_FOOTER: ""
        SLACK_TITLE: LSST metadetect tests failing on lsst-dev
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
